### ISSUE TITLE
Jio no longer allows setting password

### ISSUE THREAD

**Issue by saifshaikh1805** [nrjdalal/JioTV-Next#4]
Need OTP login

**Comment by nrjdalal** [comment]
@saifshaikh1805 you are welcome to change current login to otp based login, currently I’m not getting any free time to do the updates myself but would appreciate pull requests

*the comment is based on response at issue#3

**Comment by saifshaikh1805** [comment]
Cool, I'll look into it.

**Comment by nrjdalal** [comment]
switched to otp @saifshaikh1805
check if it is working

**Comment by saifshaikh1805** [comment]
OTP login is working well.. Thanks!
